export const products = [
  {
    _id: '1',
    name: 'W 190',
    price: 7000,
    image: '/images/imgproduct.jpg',
    category: 'Homme',
    brand: ' Nike',
    countInStock: 6,
    description: 'Nikel',
  },
  {
    _id: '2',
    name: 'W 190',
    price: 7000,
    image: '/images/imgproduct.jpg',
    category: 'Homme',
    brand: ' Nike',
    countInStock: 6,
    description: 'Nikel',
  },
  {
    _id: '3',
    name: 'W 890',
    price: 15000,
    image: '/images/imgproduct.jpg',
    category: 'Femme',
    brand: ' Nike',
    countInStock: 6,
    description: 'Nikel',
  },
  {
    _id: '4',
    name: 'W 890',
    price: 15000,
    image: '/images/imgproduct.jpg',
    category: 'Femme',
    brand: ' Nike',
    countInStock: 6,
    description: 'Nikel',
  },
];
